### ISSUE TITLE
Is `knitr` needed?

### ISSUE THREAD

**Issue by stevenleung2018** [UBC-MDS/EDAhelperR#54]
https://github.com/UBC-MDS/EDAhelperR/blob/f2211ed44bc7b38ebceb7453bf3ce032ce7085f3/vignettes/preprocess-vignette.Rmd#L20

Hi Vera, do you think `library(knitr)` is really needed?

**Comment by suuuuperNOVA** [comment]
Yes, it's required as I used `knitr::kable` to print the result. 

> https://github.com/UBC-MDS/EDAhelperR/blob/f2211ed44bc7b38ebceb7453bf3ce032ce7085f3/vignettes/preprocess-vignette.Rmd#L20
> 
> Hi Vera, do you think `library(knitr)` is really needed?

**Comment by stevenleung2018** [comment]
OK.  I understand now.  Thanks.
